# Generated by Django 4.1.5 on 2023-07-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='profile_name',
            field=models.CharField(default='Python Developer', max_length=100),
            preserve_default=False,
        ),
    ]
