# Generated by Django 4.1.5 on 2023-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_developer_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='career_objective',
            field=models.CharField(default='Python Developer offering 5+ years of extensive experience and exceptional analytical and critical thinking skills. Delivers a proactive approach, great work ethic, and the ability to function well in fast-paced/deadline-driven team environments.', max_length=1000),
            preserve_default=False,
        ),
    ]
